/*
###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID vlsi011.iittp.ac.in)
#  Generated on:      Sun Mar 15 13:32:24 2026
#  Design:            top_3d_jscan
#  Command:           saveNetlist outputs/jscan_final.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Mar 15 2026 13:11:37 IST (Mar 15 2026 07:41:37 UTC)
// Verification Directory fv/top_3d_jscan 
module top_3d_jscan (
	scan_clk, 
	reset_n, 
	scan_in, 
	test_enable, 
	fault_flag);
   input scan_clk;
   input reset_n;
   input scan_in;
   input test_enable;
   output fault_flag;

   // Internal wires
   wire [1:0] mode_sel;
   wire [3:0] col_addr;
   wire [7:0] TIER1_MSS_scan_chain;
   wire [7:0] TIER2_MSS_scan_chain;
   wire [7:0] TIER3_MSS_scan_chain;
   wire [1:0] tier_sel;
   wire \GTC_col_addr[1]_125 ;
   wire \GTC_col_addr[3]_127 ;
   wire TIER1_ras_out;
   wire TIER1_sas_out;
   wire TIER1_tsv_out;
   wire TIER2_ras_out;
   wire TIER2_sas_out;
   wire TIER2_tsv_out;
   wire TIER3_ras_out;
   wire TIER3_sas_out;
   wire TIER3_tsv_out;
   wire capture_en;
   wire misr_out_t1;
   wire misr_out_t2;
   wire misr_out_t3;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;

   SDFF \GTC_col_addr_reg[3]  (.CK(scan_clk),
	.D(n_87),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(\GTC_col_addr[3]_127 ));
   SDFF \GTC_mode_sel_reg[0]  (.CK(scan_clk),
	.D(n_83),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(mode_sel[0]));
   SDFF \GTC_mode_sel_reg[1]  (.CK(scan_clk),
	.D(n_84),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(mode_sel[1]));
   SDFF TIER3_MISR_signature_reg (.CK(scan_clk),
	.D(n_88),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(misr_out_t3));
   SDFF TIER2_MISR_signature_reg (.CK(scan_clk),
	.D(n_85),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(misr_out_t2));
   SDFF TIER1_MISR_signature_reg (.CK(scan_clk),
	.D(n_81),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(misr_out_t1));
   MUXB2RMX1 g1028__2398 (.S(n_16),
	.O(n_88),
	.EB(n_86),
	.B(n_38),
	.A(misr_out_t3));
   MUXB2RMX1 g1021__5107 (.S(test_enable),
	.O(n_87),
	.EB(n_86),
	.B(n_54),
	.A(\GTC_col_addr[3]_127 ));
   MUXB2RMX1 g1029__6260 (.S(n_18),
	.O(n_85),
	.EB(n_86),
	.B(misr_out_t2),
	.A(n_48));
   OAI12RMXSP g1020__4319 (.O(n_84),
	.B2(n_82),
	.B1(n_31),
	.A1(n_80));
   MUXB2RMX1 g1019__8428 (.S(n_82),
	.O(n_83),
	.EB(n_86),
	.B(mode_sel[0]),
	.A(n_23));
   MUXB2RMX1 g1030__5526 (.S(n_25),
	.O(n_81),
	.EB(n_86),
	.B(misr_out_t1),
	.A(n_46));
   SDFF \GTC_col_addr_reg[2]  (.CK(scan_clk),
	.D(n_79),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(col_addr[2]));
   SDFF TIER1_LC_scan_out_reg (.CK(scan_clk),
	.D(n_68),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER1_tsv_out));
   SDFF \TIER2_MSS_scan_chain_reg[7]  (.CK(scan_clk),
	.D(n_66),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER2_sas_out));
   SDFF \TIER1_MSS_scan_chain_reg[2]  (.CK(scan_clk),
	.D(n_63),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER1_MSS_scan_chain[2]));
   SDFF \TIER1_MSS_scan_chain_reg[3]  (.CK(scan_clk),
	.D(n_60),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER1_MSS_scan_chain[3]));
   SDFF \TIER1_MSS_scan_chain_reg[4]  (.CK(scan_clk),
	.D(n_59),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER1_MSS_scan_chain[4]));
   SDFF \TIER1_MSS_scan_chain_reg[5]  (.CK(scan_clk),
	.D(n_78),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER1_MSS_scan_chain[5]));
   SDFF \TIER1_MSS_scan_chain_reg[6]  (.CK(scan_clk),
	.D(n_61),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER1_MSS_scan_chain[6]));
   SDFF TIER2_LC_scan_out_reg (.CK(scan_clk),
	.D(n_64),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER2_tsv_out));
   SDFF \TIER1_MSS_scan_chain_reg[7]  (.CK(scan_clk),
	.D(n_62),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER1_sas_out));
   SDFF \TIER2_MSS_scan_chain_reg[4]  (.CK(scan_clk),
	.D(n_77),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER2_MSS_scan_chain[4]));
   SDFF \TIER2_MSS_scan_chain_reg[1]  (.CK(scan_clk),
	.D(n_72),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER2_MSS_scan_chain[1]));
   SDFF \TIER2_MSS_scan_chain_reg[2]  (.CK(scan_clk),
	.D(n_71),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER2_MSS_scan_chain[2]));
   SDFF \TIER2_MSS_scan_chain_reg[3]  (.CK(scan_clk),
	.D(n_69),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER2_MSS_scan_chain[3]));
   SDFF \TIER2_MSS_scan_chain_reg[5]  (.CK(scan_clk),
	.D(n_70),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER2_MSS_scan_chain[5]));
   SDFF \TIER1_MSS_scan_chain_reg[0]  (.CK(scan_clk),
	.D(n_76),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER1_MSS_scan_chain[0]));
   SDFF \TIER2_MSS_scan_chain_reg[6]  (.CK(scan_clk),
	.D(n_67),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER2_MSS_scan_chain[6]));
   SDFF \TIER1_MSS_scan_chain_reg[1]  (.CK(scan_clk),
	.D(n_65),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER1_MSS_scan_chain[1]));
   SDFF \TIER2_MSS_scan_chain_reg[0]  (.CK(scan_clk),
	.D(n_74),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER2_MSS_scan_chain[0]));
   ND3RMXSP g1022__6783 (.O(n_80),
	.I3(mode_sel[1]),
	.I2(reset_n),
	.I1(n_82));
   SDFF \TIER3_MSS_scan_chain_reg[7]  (.CK(scan_clk),
	.D(n_52),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER3_sas_out));
   SDFF \TIER3_MSS_scan_chain_reg[0]  (.CK(scan_clk),
	.D(n_49),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER3_MSS_scan_chain[0]));
   SDFF \TIER3_MSS_scan_chain_reg[6]  (.CK(scan_clk),
	.D(n_44),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER3_MSS_scan_chain[6]));
   SDFF \TIER3_MSS_scan_chain_reg[1]  (.CK(scan_clk),
	.D(n_51),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER3_MSS_scan_chain[1]));
   SDFF \TIER3_MSS_scan_chain_reg[2]  (.CK(scan_clk),
	.D(n_56),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER3_MSS_scan_chain[2]));
   SDFF \TIER3_MSS_scan_chain_reg[4]  (.CK(scan_clk),
	.D(n_42),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER3_MSS_scan_chain[4]));
   AOI12RMXSP g1031__3680 (.O(n_79),
	.B2(n_36),
	.B1(n_2),
	.A1(n_86));
   SDFF TIER3_LC_scan_out_reg (.CK(scan_clk),
	.D(n_58),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER3_tsv_out));
   SDFF TIER2_PRAS_scan_out_reg (.CK(scan_clk),
	.D(n_39),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER2_ras_out));
   SDFF TIER3_PRAS_scan_out_reg (.CK(scan_clk),
	.D(n_41),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER3_ras_out));
   SDFF TIER1_PRAS_scan_out_reg (.CK(scan_clk),
	.D(n_43),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER1_ras_out));
   SDFF \TIER3_MSS_scan_chain_reg[5]  (.CK(scan_clk),
	.D(n_53),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER3_MSS_scan_chain[5]));
   SDFF \TIER3_MSS_scan_chain_reg[3]  (.CK(scan_clk),
	.D(n_57),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(TIER3_MSS_scan_chain[3]));
   MUXB2RMX1 g1074__1617 (.S(n_75),
	.O(n_78),
	.EB(n_86),
	.B(TIER1_MSS_scan_chain[5]),
	.A(TIER1_MSS_scan_chain[4]));
   MUXB2RMX1 g1086__2802 (.S(n_73),
	.O(n_77),
	.EB(n_86),
	.B(TIER2_MSS_scan_chain[4]),
	.A(TIER2_MSS_scan_chain[3]));
   MUXB2RMX1 g1081__1705 (.S(n_75),
	.O(n_76),
	.EB(n_86),
	.B(TIER1_MSS_scan_chain[0]),
	.A(scan_in));
   MUXB2RMX1 g1082__5122 (.S(n_73),
	.O(n_74),
	.EB(n_86),
	.B(TIER2_MSS_scan_chain[0]),
	.A(scan_in));
   MUXB2RMX1 g1083__8246 (.S(n_73),
	.O(n_72),
	.EB(n_86),
	.B(TIER2_MSS_scan_chain[1]),
	.A(TIER2_MSS_scan_chain[0]));
   MUXB2RMX1 g1084__7098 (.S(n_73),
	.O(n_71),
	.EB(n_86),
	.B(TIER2_MSS_scan_chain[2]),
	.A(TIER2_MSS_scan_chain[1]));
   MUXB2RMX1 g1089__6131 (.S(n_73),
	.O(n_70),
	.EB(n_86),
	.B(TIER2_MSS_scan_chain[5]),
	.A(TIER2_MSS_scan_chain[4]));
   MUXB2RMX1 g1085__1881 (.S(n_73),
	.O(n_69),
	.EB(n_86),
	.B(TIER2_MSS_scan_chain[3]),
	.A(TIER2_MSS_scan_chain[2]));
   SDFF \GTC_col_addr_reg[1]  (.CK(scan_clk),
	.D(n_35),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(\GTC_col_addr[1]_125 ));
   SDFF \GTC_tier_sel_reg[1]  (.CK(scan_clk),
	.D(n_34),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(tier_sel[1]));
   MUXB2RMX1 g1090__5115 (.S(n_24),
	.O(n_68),
	.EB(n_86),
	.B(scan_in),
	.A(TIER1_tsv_out));
   MUXB2RMX1 g1091__7482 (.S(n_73),
	.O(n_67),
	.EB(n_86),
	.B(TIER2_MSS_scan_chain[6]),
	.A(TIER2_MSS_scan_chain[5]));
   MUXB2RMX1 g1092__4733 (.S(n_73),
	.O(n_66),
	.EB(n_86),
	.B(TIER2_sas_out),
	.A(TIER2_MSS_scan_chain[6]));
   MUXB2RMX1 g1093__6161 (.S(n_75),
	.O(n_65),
	.EB(n_86),
	.B(TIER1_MSS_scan_chain[1]),
	.A(TIER1_MSS_scan_chain[0]));
   MUXB2RMX1 g1064__9315 (.S(n_20),
	.O(n_64),
	.EB(n_86),
	.B(scan_in),
	.A(TIER2_tsv_out));
   MUXB2RMX1 g1095__9945 (.S(n_75),
	.O(n_63),
	.EB(n_86),
	.B(TIER1_MSS_scan_chain[2]),
	.A(TIER1_MSS_scan_chain[1]));
   MUXB2RMX1 g1065__2883 (.S(n_75),
	.O(n_62),
	.EB(n_86),
	.B(TIER1_sas_out),
	.A(TIER1_MSS_scan_chain[6]));
   MUXB2RMX1 g1067__2346 (.S(n_75),
	.O(n_61),
	.EB(n_86),
	.B(TIER1_MSS_scan_chain[6]),
	.A(TIER1_MSS_scan_chain[5]));
   MUXB2RMX1 g1069__1666 (.S(n_75),
	.O(n_60),
	.EB(n_86),
	.B(TIER1_MSS_scan_chain[3]),
	.A(TIER1_MSS_scan_chain[2]));
   MUXB2RMX1 g1071__7410 (.S(n_75),
	.O(n_59),
	.EB(n_86),
	.B(TIER1_MSS_scan_chain[4]),
	.A(TIER1_MSS_scan_chain[3]));
   MUXB2RMX1 g1094__6417 (.S(n_15),
	.O(n_58),
	.EB(n_86),
	.B(scan_in),
	.A(TIER3_tsv_out));
   MUXB2RMX1 g1072__5477 (.S(n_55),
	.O(n_57),
	.EB(n_86),
	.B(TIER3_MSS_scan_chain[2]),
	.A(TIER3_MSS_scan_chain[3]));
   MUXB2RMX1 g1073__2398 (.S(n_55),
	.O(n_56),
	.EB(n_86),
	.B(TIER3_MSS_scan_chain[1]),
	.A(TIER3_MSS_scan_chain[2]));
   XOR2RMXSP g1032__5107 (.O(n_54),
	.I2(n_50),
	.I1(\GTC_col_addr[3]_127 ));
   MUXB2RMX1 g1087__6260 (.S(n_55),
	.O(n_53),
	.EB(n_86),
	.B(TIER3_MSS_scan_chain[4]),
	.A(TIER3_MSS_scan_chain[5]));
   MUXB2RMX1 g1088__4319 (.S(n_55),
	.O(n_52),
	.EB(n_86),
	.B(TIER3_MSS_scan_chain[6]),
	.A(TIER3_sas_out));
   MUXB2RMX1 g1063__8428 (.S(n_55),
	.O(n_51),
	.EB(n_86),
	.B(TIER3_MSS_scan_chain[0]),
	.A(TIER3_MSS_scan_chain[1]));
   SDFF GTC_fault_flag_reg (.CK(scan_clk),
	.D(n_33),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(fault_flag));
   ND3RMXSP g1027__5526 (.O(n_82),
	.I3(\GTC_col_addr[3]_127 ),
	.I2(n_50),
	.I1(test_enable));
   MUXB2RMX1 g1070__6783 (.S(n_55),
	.O(n_49),
	.EB(n_86),
	.B(scan_in),
	.A(TIER3_MSS_scan_chain[0]));
   OAI22B2RMX1 g1098__3680 (.O(n_48),
	.B2B(misr_out_t2),
	.B1B(n_47),
	.A2(misr_out_t2),
	.A1(n_47));
   OAI22B2RMX1 g1099__1617 (.O(n_46),
	.B2B(misr_out_t1),
	.B1B(n_45),
	.A2(misr_out_t1),
	.A1(n_45));
   MUXB2RMX1 g1066__2802 (.S(n_55),
	.O(n_44),
	.EB(n_86),
	.B(TIER3_MSS_scan_chain[5]),
	.A(TIER3_MSS_scan_chain[6]));
   OAI12RMXSP g1104__1705 (.O(n_43),
	.B2(n_30),
	.B1(n_40),
	.A1(n_32));
   MUXB2RMX1 g1068__5122 (.S(n_55),
	.O(n_42),
	.EB(n_86),
	.B(TIER3_MSS_scan_chain[3]),
	.A(TIER3_MSS_scan_chain[4]));
   OAI12RMXSP g1105__8246 (.O(n_41),
	.B2(n_28),
	.B1(n_40),
	.A1(n_29));
   OAI12RMXSP g1107__7098 (.O(n_39),
	.B2(n_26),
	.B1(n_40),
	.A1(n_27));
   OAI22B2RMX1 g1097__6131 (.O(n_38),
	.B2B(misr_out_t3),
	.B1B(n_37),
	.A2(misr_out_t3),
	.A1(n_37));
   OAI112RMXSP g1047__1881 (.O(n_36),
	.C2(col_addr[2]),
	.C1(n_9),
	.B1(n_17),
	.A1(test_enable));
   SDFF \GTC_tier_sel_reg[0]  (.CK(scan_clk),
	.D(n_21),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(tier_sel[0]));
   AOI12RMXSP g1096__5115 (.O(n_35),
	.B2(n_14),
	.B1(n_1),
	.A1(n_86));
   AOI12RMXSP g1106__7482 (.O(n_34),
	.B2(n_11),
	.B1(n_3),
	.A1(n_86));
   AOI12RMXSP g1101__4733 (.O(n_33),
	.B2(n_8),
	.B1(n_4),
	.A1(n_86));
   SDFF GTC_shift_en_reg (.CK(scan_clk),
	.D(n_13),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(col_addr[0]));
   OAI12RMXSP g1111__6161 (.O(n_32),
	.B2(n_30),
	.B1(n_31),
	.A1(TIER1_ras_out));
   OAI12RMXSP g1113__9315 (.O(n_29),
	.B2(n_28),
	.B1(n_31),
	.A1(TIER3_ras_out));
   OAI12RMXSP g1114__9945 (.O(n_27),
	.B2(n_26),
	.B1(n_31),
	.A1(TIER2_ras_out));
   OR2B1RMXLP g1122__2883 (.O(n_25),
	.I1(n_30),
	.B1(capture_en));
   NR2RMX1 g1127__2346 (.O(n_24),
	.I2(n_30),
	.I1(n_19));
   AOI222RMX1 g1117__1666 (.O(n_47),
	.C2(TIER2_tsv_out),
	.C1(mode_sel[1]),
	.B2(TIER2_sas_out),
	.B1(n_23),
	.A2(TIER2_ras_out),
	.A1(n_22));
   AOI222RMX1 g1115__7410 (.O(n_37),
	.C2(TIER3_tsv_out),
	.C1(mode_sel[1]),
	.B2(TIER3_sas_out),
	.B1(n_23),
	.A2(TIER3_ras_out),
	.A1(n_22));
   AOI222RMX1 g1116__6417 (.O(n_45),
	.C2(TIER1_tsv_out),
	.C1(mode_sel[1]),
	.B2(TIER1_sas_out),
	.B1(n_23),
	.A2(TIER1_ras_out),
	.A1(n_22));
   OR2B1RMXLP g1123__5477 (.O(n_75),
	.I1(n_30),
	.B1(n_23));
   AO122RMX1 g1108__2398 (.O(n_21),
	.C2(tier_sel[0]),
	.C1(n_12),
	.B2(n_10),
	.B1(test_enable),
	.A1(n_86));
   NR2RMX1 g1128__5107 (.O(n_20),
	.I2(n_26),
	.I1(n_19));
   OR2B1RMXLP g1121__6260 (.O(n_18),
	.I1(n_26),
	.B1(capture_en));
   INVCKRMX1 g1062 (.O(n_50),
	.I(n_17));
   OR2RMXLP g1129__4319 (.O(n_40),
	.I2(n_31),
	.I1(n_5));
   SDFF GTC_capture_en_reg (.CK(scan_clk),
	.D(n_6),
	.TD(1'b0),
	.SEL(1'b0),
	.Q(capture_en));
   OR2B1RMXLP g1130__8428 (.O(n_73),
	.I1(n_26),
	.B1(n_23));
   AN2B1RMXLP g1119__5526 (.O(n_16),
	.I1(capture_en),
	.B1(n_28));
   NR2RMX1 g1120__6783 (.O(n_15),
	.I2(n_28),
	.I1(n_19));
   AN2B1RMXLP g1124__3680 (.O(n_55),
	.I1(n_23),
	.B1(n_28));
   OAI112RMXSP g1110__1617 (.O(n_14),
	.C2(col_addr[0]),
	.C1(\GTC_col_addr[1]_125 ),
	.B1(n_0),
	.A1(test_enable));
   MUXB2RMX1 g1109__2802 (.S(col_addr[0]),
	.O(n_13),
	.EB(n_86),
	.B(n_12),
	.A(test_enable));
   OAI12B2RMX1 g1125__1705 (.O(n_11),
	.B2(n_7),
	.B1(n_10),
	.A1(test_enable));
   ND2RMX1 g1112__5122 (.O(n_17),
	.I2(col_addr[2]),
	.I1(n_9));
   OAI13RMX1 g1126__8246 (.O(n_8),
	.B3(misr_out_t3),
	.B2(misr_out_t2),
	.B1(misr_out_t1),
	.A1(test_enable));
   OR2B1RMXLP g1131__7098 (.O(n_26),
	.I1(n_7),
	.B1(test_enable));
   MUXB2RMX1 g1100__6131 (.S(test_enable),
	.O(n_6),
	.EB(n_86),
	.B(col_addr[0]),
	.A(capture_en));
   ND2RMX1 g1135__1881 (.O(n_31),
	.I2(n_22),
	.I1(reset_n));
   OR2B1RMXLP g1132__5115 (.O(n_30),
	.I1(n_10),
	.B1(test_enable));
   XOR2RMXSP g1133__7482 (.O(n_5),
	.I2(col_addr[0]),
	.I1(col_addr[2]));
   ND2RMX1 g1136__4733 (.O(n_4),
	.I2(fault_flag),
	.I1(n_12));
   ND3RMXSP g1134__6161 (.O(n_28),
	.I3(tier_sel[0]),
	.I2(tier_sel[1]),
	.I1(test_enable));
   ND2RMX1 g1142__9315 (.O(n_3),
	.I2(tier_sel[1]),
	.I1(n_12));
   ND2RMX1 g1141__9945 (.O(n_2),
	.I2(col_addr[2]),
	.I1(n_12));
   ND2RMX1 g1137__2883 (.O(n_1),
	.I2(\GTC_col_addr[1]_125 ),
	.I1(n_12));
   INVCKRMX1 g1118 (.O(n_9),
	.I(n_0));
   ND2RMX1 g1144__2346 (.O(n_0),
	.I2(\GTC_col_addr[1]_125 ),
	.I1(col_addr[0]));
   OR2B1RMXLP g1138__1666 (.O(n_19),
	.I1(mode_sel[0]),
	.B1(mode_sel[1]));
   AN2B1NRMXLP g1139__7410 (.O(n_22),
	.I1(mode_sel[0]),
	.B1(mode_sel[1]));
   OR2B1RMXLP g1143__6417 (.O(n_7),
	.I1(tier_sel[0]),
	.B1(tier_sel[1]));
   OR2B1RMXLP g1145__5477 (.O(n_10),
	.I1(tier_sel[1]),
	.B1(tier_sel[0]));
   NR2RMX1 g1140__2398 (.O(n_23),
	.I2(mode_sel[1]),
	.I1(mode_sel[0]));
   INVRMX1 g1147 (.O(n_86),
	.I(reset_n));
   INVCKRMX1 g1146 (.O(n_12),
	.I(test_enable));
endmodule

